### ISSUE TITLE
https://releaser.richardhagen.no/ website is down

### ISSUE THREAD

**Issue by netx123** [Richard87/releaser#31] opened 2018-08-31 07:45 UTC
Looks like the website is down, I don't know if this is a temporary issue or not.

As email notifications have not worked for some time now, I've been relying on being able to browse to the website to manually check for github updates.

**Comment by AlexWayfer** [comment] 2018-08-31 07:48
Duplicate of https://github.com/Richard87/releaser/issues/30#issuecomment-416865405, I guess.

**Comment by Richard87** [comment] 2018-08-31 08:46
Hi, this is permanent, the server is shutdown and the project is abandonded :(

There where to many flawes in the arcitecture that would require a rewrite, and there are so many better projects out there, that I reccomend some of those :)

For example here are many examples: https://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases


Good luck!

**Closed as completed by Richard87** 2018-08-31 08:46 UTC
