### ISSUE TITLE
Forked Projects

### ISSUE THREAD

**Issue by demonspork** [Richard87/releaser#11] opened 2017-04-25 00:29 UTC
I can't seem to find projects to add if they are forked from the original unmaintained repo.
For example:
https://github.com/Jackett/Jackett
I can't find in the search, but I can find the upstream which hasn't been maintained in over a year since the fork.

**Comment by Richard87** [comment] 2017-05-25 16:51
This is a duplicate of #7

**Closed as completed by Richard87** 2017-05-25 16:51 UTC
