### ISSUE TITLE
Links redirection

### ISSUE THREAD

**Issue by loiclouvet** [Richard87/releaser#14] opened 2017-05-26 11:23 UTC
All your links redirect to http://www.create-it.no/

For instance: 
http://email.richardhagen.no/c/eJwVjjtuxDAMBU9jdzFEmdanULFN7kGRlC1k11rYSnL9KMArZvCakWSNBjfXFAg5elKIHIW4aOEim9FVvayQzYTm_q2lL7ueelFXmY_EZCI6k_3GAUtBA2LdtnqIFGgLYX6mo_f3Pa2PyX6O7bUf33nh9hpSiDW39jXwUuL-cVKvPzp0_K_a_yFItDaj8wasZwQvHpEMAYJldiTRwWidr_RslUfkyLtFuZ2l0sm6lOsPFMdGvA

I hope it's not intentional..

**Comment by AlexWayfer** [comment] 2017-05-26 19:36
Duplicate of #13 :man_shrugging:

**Comment by Richard87** [comment] 2017-05-27 09:42
Thanks! I will fix it ASAP!

**Comment by Richard87** [comment] 2017-05-27 09:48
It has been fixed, but will probably take 2 hours before the DNS has been updated... Thanks for reporting the issue!

**Closed as completed by Richard87** 2017-05-27 09:48 UTC
